ekf_localizer_node:
  ros__parameters:
    init:
      x: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # x y theta, nu, omega, alpha
      P: [1e-9,  0.0,  0.0, 0.0, 0.0, 0.0,
           0.0, 1e-9,  0.0, 0.0, 0.0, 0.0,
           0.0,  0.0, 1e-9, 0.0, 0.0, 0.0,
           0.0,  0.0,  0.0, 1.0, 0.0, 0.0,
           0.0,  0.0,  0.0, 0.0, 1.0, 0.0,
           0.0,  0.0,  0.0, 0.0, 0.0, 1.0]
    eps:  # process noise
      x: 0.001
      y: 0.001
      theta: 0.01
      nu: 0.71
      omega: 0.51
      alpha: 0.51
    tau:  # measurement noise
      x: 0.2
      y: 0.2
      theta: 0.1
      nu: 0.1
      omega: 0.05
      alpha: 0.1
