ekf_localizer_node:
  ros__parameters:
    init:
      x: [0.0, 0.0, 2.5, 0.0, 0.0, 0.0]
      P: [100.0,   0.0, 0.0,  0.0, 0.0,  0.0,
            0.0, 100.0, 0.0,  0.0, 0.0,  0.0,
            0.0,   0.0, 1.0,  0.0, 0.0,  0.0,
            0.0,   0.0, 0.0, 10.0, 0.0,  0.0,
            0.0,   0.0, 0.0,  0.0, 1.0,  0.0,
            0.0,   0.0, 0.0,  0.0, 0.0, 10.0]
    eps:
      x: 0.0
      y: 0.0
      theta: 0.0
      nu: 0.0
      omega: 0.2
      alpha: 0.1
    tau:
      x: 0.0  # if your gps does not provide this value, you will have to set.
      y: 0.0  # if your gps does not provide this value, you will have to set.
      theta: 0.1
      omega: 0.05
      alpha: 0.1
